name: burodeconfianza
favicon: null
layout_spectrum: 0.12525879545137286
typography_spectrum: 0.3148334687575698
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.22708959435112774
  lightness: 0.362440777476877
  saturation: 0.6169152054935694
  rhythmicContrast: 0.03824285208247602
purpose: []
