name: burodeconfianza
favicon: null
layout_spectrum: 0.43471
typography_spectrum: 0.84223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cfcfcf'
    - '#828284'
    - '#053a66'
    - '#466881'
  brandStrength: 0.22708959435112774
  lightness: 0.362440777476877
  saturation: 0.6169152054935694
  rhythmicContrast: 0.03824285208247602
purpose: []
